package com.dataconnect.app

/** Backend V2.0.5 API route registry. */
object DataConnectApiRoutes {
    const val HEALTH = "/api/health"
    const val DASHBOARD = "/api/v2/wallet"
    const val REGISTER = "/api/v2/auth/register"
    const val LOGIN = "/api/v2/auth/login"
    const val LOGOUT = "/api/v2/auth/logout"
    const val PROFILE = "/api/v2/account/profile"
    const val SETTINGS = "/api/v2/account/settings"
    const val WALLET = "/api/v2/wallet"
    const val TRANSACTIONS = "/api/v2/wallet/transactions"
    const val DATA_PLANS = "/api/v2/data/plans"
    const val PURCHASE_DATA = "/api/v2/data/purchase"
    const val AIRTIME_PURCHASE = "/api/v2/airtime/purchase"
    const val ORDERS = "/api/v2/orders"
    const val AIRTIME_REQUESTS = "/api/v2/orders"
    const val SHARES = "/api/v2/shares"
    const val BUY_SHARE = "/api/v2/shares/purchase"
    const val HOLDINGS = "/api/v2/shares/portfolio"
    const val SHARE_RETURNS = "/api/v2/shares/portfolio"
    const val WITHDRAWALS = "/api/v2/withdrawals"
    const val NOTIFICATIONS = "/api/v2/notifications"
    const val APP_VERSION = "/api/v2/app/version"
    const val ADMIN_USERS = "/api/v2/admin/users"
    const val ADMIN_TRANSACTIONS = "/api/v2/admin/transactions"
    const val ADMIN_WITHDRAWALS = "/api/v2/admin/withdrawals"
    const val ADMIN_SETTINGS = "/api/v2/admin/settings"
}
